package au.com.nicta.ct.db.hibernate;
// Generated 24/01/2011 2:48:48 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * CtAnnotationsTypes generated by hbm2java
 */
public class CtAnnotationsTypes  implements java.io.Serializable {


     private int pkAnnotationType;
     private String value;
     private Set ctAnnotationses = new HashSet(0);

    public CtAnnotationsTypes() {
    }

	
    public CtAnnotationsTypes(int pkAnnotationType, String name) {
        this.pkAnnotationType = pkAnnotationType;
        this.value = name;
    }
    public CtAnnotationsTypes(int pkAnnotationType, String name, Set ctAnnotationses) {
       this.pkAnnotationType = pkAnnotationType;
       this.value = name;
       this.ctAnnotationses = ctAnnotationses;
    }
   
    public int getPkAnnotationType() {
        return this.pkAnnotationType;
    }
    
    public void setPkAnnotationType(int pkAnnotationType) {
        this.pkAnnotationType = pkAnnotationType;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public Set getCtAnnotationses() {
        return this.ctAnnotationses;
    }
    
    public void setCtAnnotationses(Set ctAnnotationses) {
        this.ctAnnotationses = ctAnnotationses;
    }




}


