package au.com.nicta.ct.db.hibernate;
// Generated 24/01/2011 2:48:48 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * CtCoordinates generated by hbm2java
 */
public class CtCoordinates  implements java.io.Serializable {


     private int pkCoordinate;
     private CtCoordinatesTypes ctCoordinatesTypes; 
     private Integer value;
     private String name;
     private Set ctExperimentsAxesesForFkCoordinate2 = new HashSet(0);
     private Set ctImagesCoordinateses = new HashSet(0);
     private Set ctExperimentsAxesesForFkCoordinate1 = new HashSet(0);

    public CtCoordinates() {
    }

	
    public CtCoordinates(int pkCoordinate) {
        this.pkCoordinate = pkCoordinate;
    }
    public CtCoordinates(int pkCoordinate, CtCoordinatesTypes ctCoordinatesTypes, Integer value, String name,Set ctExperimentsAxesesForFkCoordinate2, Set ctImagesCoordinateses, Set ctExperimentsAxesesForFkCoordinate1) {
       this.pkCoordinate = pkCoordinate;
       this.ctCoordinatesTypes = ctCoordinatesTypes;
       this.value = value;
       this.name = name;
       this.ctExperimentsAxesesForFkCoordinate2 = ctExperimentsAxesesForFkCoordinate2;
       this.ctImagesCoordinateses = ctImagesCoordinateses;
       this.ctExperimentsAxesesForFkCoordinate1 = ctExperimentsAxesesForFkCoordinate1;
    }
   
    public int getPkCoordinate() {
        return this.pkCoordinate;
    }
    
    public void setPkCoordinate(int pkCoordinate) {
        this.pkCoordinate = pkCoordinate;
    }
    public CtCoordinatesTypes getCtCoordinatesTypes() {
        return this.ctCoordinatesTypes;
    }
    
    public void setCtCoordinatesTypes(CtCoordinatesTypes ctCoordinatesTypes) {
        this.ctCoordinatesTypes = ctCoordinatesTypes;
    }
    public Integer getValue() {
        return this.value;
    }
    
    public void setValue(Integer value) {
        this.value = value;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }
    public Set getCtExperimentsAxesesForFkCoordinate2() {
        return this.ctExperimentsAxesesForFkCoordinate2;
    }
    
    public void setCtExperimentsAxesesForFkCoordinate2(Set ctExperimentsAxesesForFkCoordinate2) {
        this.ctExperimentsAxesesForFkCoordinate2 = ctExperimentsAxesesForFkCoordinate2;
    }
    public Set getCtImagesCoordinateses() {
        return this.ctImagesCoordinateses;
    }
    
    public void setCtImagesCoordinateses(Set ctImagesCoordinateses) {
        this.ctImagesCoordinateses = ctImagesCoordinateses;
    }
    public Set getCtExperimentsAxesesForFkCoordinate1() {
        return this.ctExperimentsAxesesForFkCoordinate1;
    }
    
    public void setCtExperimentsAxesesForFkCoordinate1(Set ctExperimentsAxesesForFkCoordinate1) {
        this.ctExperimentsAxesesForFkCoordinate1 = ctExperimentsAxesesForFkCoordinate1;
    }




}


