package au.com.nicta.ct.db.hibernate;
// Generated 24/01/2011 2:48:48 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * CtCoordinatesTypes generated by hbm2java
 */
public class CtCoordinatesTypes  implements java.io.Serializable {


     private int pkCoordinateType;
     private String name;
     private Set ctCoordinateses = new HashSet(0);

    public CtCoordinatesTypes() {
    }

	
    public CtCoordinatesTypes(int pkCoordinateType, String name) {
        this.pkCoordinateType = pkCoordinateType;
        this.name = name;
    }
    public CtCoordinatesTypes(int pkCoordinateType, String name, Set ctCoordinateses) {
       this.pkCoordinateType = pkCoordinateType;
       this.name = name;
       this.ctCoordinateses = ctCoordinateses;
    }
   
    public int getPkCoordinateType() {
        return this.pkCoordinateType;
    }
    
    public void setPkCoordinateType(int pkCoordinateType) {
        this.pkCoordinateType = pkCoordinateType;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getCtCoordinateses() {
        return this.ctCoordinateses;
    }
    
    public void setCtCoordinateses(Set ctCoordinateses) {
        this.ctCoordinateses = ctCoordinateses;
    }




}


