package au.com.nicta.ct.db.hibernate;
// Generated 24/01/2011 2:48:48 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * CtDetections generated by hbm2java
 */
public class CtDetections  implements java.io.Serializable {


     private int pkDetection;
     private CtSolutions ctSolutions;
     private CtImages ctImages;
     private String location;
     private String boundary;
     private Set ctTracksDetectionses = new HashSet(0);

    public CtDetections() {
    }

    public CtDetections(int pkDetection) {
        this.pkDetection = pkDetection;
    }
    
    public CtDetections(int pkDetection, CtSolutions ctSolutions, CtImages ctImages, String location, String boundary, Set ctTracksDetectionses) {
       this.pkDetection = pkDetection;
       this.ctSolutions = ctSolutions;
       this.ctImages = ctImages;
       this.location = location;
       this.boundary = boundary;
       this.ctTracksDetectionses = ctTracksDetectionses;
    }
   
    public int getPkDetection() {
        return this.pkDetection;
    }
    
    public void setPkDetection(int pkDetection) {
        this.pkDetection = pkDetection;
    }
    public CtSolutions getCtSolutions() {
        return this.ctSolutions;
    }
    
    public void setCtSolutions(CtSolutions ctSolutions) {
        this.ctSolutions = ctSolutions;
    }
    public CtImages getCtImages() {
        return this.ctImages;
    }
    
    public void setCtImages(CtImages ctImages) {
        this.ctImages = ctImages;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getBoundary() {
        return this.boundary;
    }
    
    public void setBoundary(String boundary) {
        this.boundary = boundary;
    }
    public Set getCtTracksDetectionses() {
        return this.ctTracksDetectionses;
    }
    
    public void setCtTracksDetectionses(Set ctTracksDetectionses) {
        this.ctTracksDetectionses = ctTracksDetectionses;
    }




}


