package au.com.nicta.ct.db.hibernate;
// Generated 24/01/2011 2:48:48 PM by Hibernate Tools 3.2.1.GA

/**
 * CtProperties generated by hbm2java
 */
public class CtEntityPropertiesTypes  implements java.io.Serializable {

    private int pkEntityPropertyType;
    private String entityName;
    private String name;
    private String type;

    public CtEntityPropertiesTypes() {
    }

	
    public CtEntityPropertiesTypes(int pkEntityPropertyType) {
        this.pkEntityPropertyType = pkEntityPropertyType;
    }

    public CtEntityPropertiesTypes(int pkEntityPropertyType, String entityName, String name, String type) {
       this.pkEntityPropertyType = pkEntityPropertyType;
       this.entityName = entityName;
       this.name = name;
       this.type = type;
    }
   
    public int getPkEntityPropertyType() {
        return this.pkEntityPropertyType;
    }
    
    public void setPkEntityPropertyType(int pkEntityPropertyType) {
        this.pkEntityPropertyType = pkEntityPropertyType;
    }

    public String getEntityName() {
        return this.entityName;
    }
    public void setEntityName(String entityName) {
        this.entityName = entityName;
    }

    public String getName() {
        return this.name;
    }    
    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return this.type;
    }
    public void setType(String type) {
        this.type = type;
    }
}


