package au.com.nicta.ct.db.hibernate;
// Generated 24/01/2011 2:48:48 PM by Hibernate Tools 3.2.1.GA


/**
 * CtProperties generated by hbm2java
 */
public class CtEntityProperties  implements java.io.Serializable {

    private int pkEntityProperty;
    private CtSolutions ctSolutions;
    private String entityName;
    private Integer entityPk;
    private String name;
    private String value;

    public CtEntityProperties() {
    }

	
    public CtEntityProperties(int pkEntityProperty) {
        this.pkEntityProperty = pkEntityProperty;
    }

    public CtEntityProperties(int pkEntityProperty, CtSolutions ctSolutions, String entityName, Integer entityPk, String name, String value) {
       this.pkEntityProperty = pkEntityProperty;
       this.ctSolutions = ctSolutions;
       this.entityName = entityName;
       this.entityPk = entityPk;
       this.name = name;
       this.value = value;
    }
   
    public int getPkEntityProperty() {
        return this.pkEntityProperty;
    }
    
    public void setPkEntityProperty(int pkEntityProperty) {
        this.pkEntityProperty = pkEntityProperty;
    }

    public CtSolutions getCtSolutions() {
        return this.ctSolutions;
    }

    public void setCtSolutions(CtSolutions ctSolutions) {
        this.ctSolutions = ctSolutions;
    }

    public String getEntityName() {
        return this.entityName;
    }
    public void setEntityName(String entityName) {
        this.entityName = entityName;
    }

    public Integer getEntityPk() {
        return this.entityPk;
    }
    public void setEntityPk(Integer tableRow) {
        this.entityPk = tableRow;
    }

    public String getName() {
        return this.name;
    }    
    public void setName(String name) {
        this.name = name;
    }

    public String getValue() {
        return this.value;
    }
    public void setValue(String value) {
        this.value = value;
    }

}


