package au.com.nicta.ct.db.hibernate;
// Generated 24/01/2011 2:48:48 PM by Hibernate Tools 3.2.1.GA



/**
 * CtExperimentsAxes generated by hbm2java
 */
public class CtExperimentsAxes  implements java.io.Serializable {


     private int pkExperimentAxis;
     private CtExperiments ctExperiments;
     private CtCoordinates ctCoordinatesByFkCoordinate2;
     private CtCoordinates ctCoordinatesByFkCoordinate1;

    public CtExperimentsAxes() {
    }

	
    public CtExperimentsAxes(int pkExperimentAxis) {
        this.pkExperimentAxis = pkExperimentAxis;
    }
    public CtExperimentsAxes(int pkExperimentAxis, CtExperiments ctExperiments, CtCoordinates ctCoordinatesByFkCoordinate2, CtCoordinates ctCoordinatesByFkCoordinate1) {
       this.pkExperimentAxis = pkExperimentAxis;
       this.ctExperiments = ctExperiments;
       this.ctCoordinatesByFkCoordinate2 = ctCoordinatesByFkCoordinate2;
       this.ctCoordinatesByFkCoordinate1 = ctCoordinatesByFkCoordinate1;
    }

    public int getPkExperimentAxis() {
        return this.pkExperimentAxis;
    }
    
    public void setPkExperimentAxis(int pkExperimentAxis) {
        this.pkExperimentAxis = pkExperimentAxis;
    }
    public CtExperiments getCtExperiments() {
        return this.ctExperiments;
    }
    
    public void setCtExperiments(CtExperiments ctExperiments) {
        this.ctExperiments = ctExperiments;
    }
    public CtCoordinates getCtCoordinatesByFkCoordinate2() {
        return this.ctCoordinatesByFkCoordinate2;
    }
    
    public void setCtCoordinatesByFkCoordinate2(CtCoordinates ctCoordinatesByFkCoordinate2) {
        this.ctCoordinatesByFkCoordinate2 = ctCoordinatesByFkCoordinate2;
    }
    public CtCoordinates getCtCoordinatesByFkCoordinate1() {
        return this.ctCoordinatesByFkCoordinate1;
    }
    
    public void setCtCoordinatesByFkCoordinate1(CtCoordinates ctCoordinatesByFkCoordinate1) {
        this.ctCoordinatesByFkCoordinate1 = ctCoordinatesByFkCoordinate1;
    }




}


