package au.com.nicta.ct.db.hibernate;
// Generated 24/01/2011 2:48:48 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * CtExperiments generated by hbm2java
 * modified by dave
 */
public class CtExperiments  implements java.io.Serializable {


     private int pkExperiment;
     private String name;
     private String uri;
     private Set ctGroupsExperimentses = new HashSet(0);
     private Set ctExperimentsAxeses = new HashSet(0);
     private Set ctImageses = new HashSet(0);
     private Set ctSolutionses = new HashSet(0);

    public CtExperiments() {
    }

	
    public CtExperiments(int pkExperiment, String name, String uri ) {
        this.pkExperiment = pkExperiment;
        this.name = name;
        this.uri = uri;
    }
    
    public CtExperiments(int pkExperiment, String name, String uri, Set ctGroupsExperimentses, Set ctExperimentsAxeses, Set ctImageses, Set ctSolutionses) {
       this.pkExperiment = pkExperiment;
       this.name = name;
       this.uri = uri;
       this.ctGroupsExperimentses = ctGroupsExperimentses;
       this.ctExperimentsAxeses = ctExperimentsAxeses;
       this.ctImageses = ctImageses;
       this.ctSolutionses = ctSolutionses;
    }
   
    public int getPkExperiment() {
        return this.pkExperiment;
    }
    
    public void setPkExperiment(int pkExperiment) {
        this.pkExperiment = pkExperiment;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUri() {
        return this.uri;
    }
    
    public void setUri(String uri) {
        this.uri = uri;
    }

    public Set getCtGroupsExperimentses() {
        return this.ctGroupsExperimentses;
    }
    public void setCtGroupsExperimentses(Set ctGroupsExperimentses) {
        this.ctGroupsExperimentses = ctGroupsExperimentses;
    }

    public Set getCtExperimentsAxeses() {
        return this.ctExperimentsAxeses;
    }
    public void setCtExperimentsAxeses(Set ctExperimentsAxeses) {
        this.ctExperimentsAxeses = ctExperimentsAxeses;
    }

    public Set getCtImageses() {
        return this.ctImageses;
    }
    public void setCtImageses(Set ctImageses) {
        this.ctImageses = ctImageses;
    }

    public Set getCtSolutionses() {
        return this.ctSolutionses;
    }
    public void setCtSolutionses(Set ctSolutionses) {
        this.ctSolutionses = ctSolutionses;
    }
}


