package au.com.nicta.ct.db.hibernate;
// Generated 24/01/2011 2:48:48 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * CtGroups generated by hbm2java
 */
public class CtGroups  implements java.io.Serializable {


     private int pkGroup;
     private String name;
     private Set ctGroupsExperimentses = new HashSet(0);
     private Set ctUsersGroupses = new HashSet(0);

    public CtGroups() {
    }
	
    public CtGroups(int pkGroup, String name) {
        this.pkGroup = pkGroup;
        this.name = name;
    }

    public CtGroups(int pkGroup, String name, Set ctGroupsExperimentses, Set ctUsersGroupses) {
       this.pkGroup = pkGroup;
       this.name = name;
       this.ctGroupsExperimentses = ctGroupsExperimentses;
       this.ctUsersGroupses = ctUsersGroupses;
    }
   
    public int getPkGroup() {
        return this.pkGroup;
    }
    
    public void setPkGroup(int pkGroup) {
        this.pkGroup = pkGroup;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getCtGroupsExperimentses() {
        return this.ctGroupsExperimentses;
    }
    
    public void setCtGroupsExperimentses(Set ctGroupsExperimentses) {
        this.ctGroupsExperimentses = ctGroupsExperimentses;
    }
    public Set getCtUsersGroupses() {
        return this.ctUsersGroupses;
    }
    
    public void setCtUsersGroupses(Set ctUsersGroupses) {
        this.ctUsersGroupses = ctUsersGroupses;
    }




}


