package au.com.nicta.ct.db.hibernate;
// Generated 24/01/2011 2:48:48 PM by Hibernate Tools 3.2.1.GA



/**
 * CtImagesCoordinates generated by hbm2java
 */
public class CtImagesCoordinates  implements java.io.Serializable {


     private int pkImageCoordinate;
     private CtCoordinates ctCoordinates;
     private CtImages ctImages;

    public CtImagesCoordinates() {
    }

	
    public CtImagesCoordinates(int pkImageCoordinate) {
        this.pkImageCoordinate = pkImageCoordinate;
    }
    public CtImagesCoordinates(int pkImageCoordinate, CtCoordinates ctCoordinates, CtImages ctImages) {
       this.pkImageCoordinate = pkImageCoordinate;
       this.ctCoordinates = ctCoordinates;
       this.ctImages = ctImages;
    }
   
    public int getPkImageCoordinate() {
        return this.pkImageCoordinate;
    }
    
    public void setPkImageCoordinate(int pkImageCoordinate) {
        this.pkImageCoordinate = pkImageCoordinate;
    }
    public CtCoordinates getCtCoordinates() {
        return this.ctCoordinates;
    }
    
    public void setCtCoordinates(CtCoordinates ctCoordinates) {
        this.ctCoordinates = ctCoordinates;
    }
    public CtImages getCtImages() {
        return this.ctImages;
    }
    
    public void setCtImages(CtImages ctImages) {
        this.ctImages = ctImages;
    }




}


