package au.com.nicta.ct.db.hibernate;
// Generated 24/01/2011 2:48:48 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * CtProperties generated by hbm2java
 */
public class CtProperties  implements java.io.Serializable {


     private int pkProperty;
     private CtPropertiesTypes ctPropertiesTypes;
     private String name;
     private String value;
     private Set ctPropertiesRangeses = new HashSet(0);

    public CtProperties() {
    }

	
    public CtProperties(int pkProperty) {
        this.pkProperty = pkProperty;
    }
    public CtProperties(int pkProperty, CtPropertiesTypes ctPropertiesTypes, String name, String value, Set ctPropertiesRangeses) {
       this.pkProperty = pkProperty;
       this.ctPropertiesTypes = ctPropertiesTypes;
       this.name = name;
       this.value = value;
       this.ctPropertiesRangeses = ctPropertiesRangeses;
    }
   
    public int getPkProperty() {
        return this.pkProperty;
    }
    
    public void setPkProperty(int pkProperty) {
        this.pkProperty = pkProperty;
    }

    public CtPropertiesTypes getCtPropertiesTypes() {
        return this.ctPropertiesTypes;
    }
    public void setCtPropertiesTypes(CtPropertiesTypes ctPropertiesTypes) {
        this.ctPropertiesTypes = ctPropertiesTypes;
    }

    public String getName() {
        return this.name;
    }    
    public void setName(String name) {
        this.name = name;
    }

    public String getValue() {
        return this.value;
    }
    public void setValue(String value) {
        this.value = value;
    }

    public Set getCtPropertiesRangeses() {
        return this.ctPropertiesRangeses;
    }    
    public void setCtPropertiesRangeses(Set ctPropertiesRangeses) {
        this.ctPropertiesRangeses = ctPropertiesRangeses;
    }

}


