package au.com.nicta.ct.db.hibernate;
// Generated 24/01/2011 2:48:48 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * CtPropertiesRanges generated by dave
 */
public class CtPropertiesRanges  implements java.io.Serializable {


     private int pkPropertyRange;
     private CtProperties ctProperties;
     private CtCoordinates ctCoordinatesByFkCoordinate2;
     private CtCoordinates ctCoordinatesByFkCoordinate1;

    public CtPropertiesRanges() {
    }

	
    public CtPropertiesRanges(int pkPropertyRange) {
        this.pkPropertyRange = pkPropertyRange;
    }
    public CtPropertiesRanges(int pkPropertyRange, CtProperties ctProperties, CtCoordinates ctCoordinatesByFkCoordinate2, CtCoordinates ctCoordinatesByFkCoordinate1 ) {
       this.pkPropertyRange = pkPropertyRange;
       this.ctProperties = ctProperties;
       this.ctCoordinatesByFkCoordinate2 = ctCoordinatesByFkCoordinate2;
       this.ctCoordinatesByFkCoordinate1 = ctCoordinatesByFkCoordinate1;
    }
   
    public int getPkPropertyRange() {
        return this.pkPropertyRange;
    }
    public void setPkPropertyRange(int pkPropertyRange) {
        this.pkPropertyRange = pkPropertyRange;
    }

    public CtProperties getCtProperties() {
        return this.ctProperties;
    }
    public void setCtProperties(CtProperties ctProperties) {
        this.ctProperties = ctProperties;
    }

    public CtCoordinates getCtCoordinatesByFkCoordinate2() {
        return this.ctCoordinatesByFkCoordinate2;
    }

    public void setCtCoordinatesByFkCoordinate2(CtCoordinates ctCoordinatesByFkCoordinate2) {
        this.ctCoordinatesByFkCoordinate2 = ctCoordinatesByFkCoordinate2;
    }
    public CtCoordinates getCtCoordinatesByFkCoordinate1() {
        return this.ctCoordinatesByFkCoordinate1;
    }

    public void setCtCoordinatesByFkCoordinate1(CtCoordinates ctCoordinatesByFkCoordinate1) {
        this.ctCoordinatesByFkCoordinate1 = ctCoordinatesByFkCoordinate1;
    }
}


