package au.com.nicta.ct.db.hibernate;
// Generated 24/01/2011 2:48:48 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * CtPropertiesTypes generated by hbm2java
 */
public class CtPropertiesTypes  implements java.io.Serializable {


     private int pkPropertyType;
     private String name;
     private Set ctPropertieses = new HashSet(0);

    public CtPropertiesTypes() {
    }

	
    public CtPropertiesTypes(int pkPropertyType, String name) {
        this.pkPropertyType = pkPropertyType;
        this.name = name;
    }
    public CtPropertiesTypes(int pkPropertyType, String name, Set ctPropertieses) {
       this.pkPropertyType = pkPropertyType;
       this.name = name;
       this.ctPropertieses = ctPropertieses;
    }
   
    public int getPkPropertyType() {
        return this.pkPropertyType;
    }
    
    public void setPkPropertyType(int pkPropertyType) {
        this.pkPropertyType = pkPropertyType;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getCtPropertieses() {
        return this.ctPropertieses;
    }
    
    public void setCtPropertieses(Set ctPropertieses) {
        this.ctPropertieses = ctPropertieses;
    }




}


