package au.com.nicta.ct.db.hibernate;
// Generated 24/01/2011 2:48:48 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * CtSolutions generated by hbm2java
 */
public class CtSolutions  implements java.io.Serializable {


     private int pkSolution;
//     private CtUwells ctUwells;
     private CtExperiments ctExperiments;
     private String name;
     private Set ctDetectionses = new HashSet(0);
     private Set ctTrackses = new HashSet(0);

    public CtSolutions() {
    }

	
    public CtSolutions(int pkSolution, String name) {
        this.pkSolution = pkSolution;
        this.name = name;
    }
//    public CtSolutions(int pkSolution, CtUwells ctUwells, String name, Set ctDetectionses, Set ctTrackses) {
    public CtSolutions(int pkSolution, CtExperiments ctExperiments, String name, Set ctDetectionses, Set ctTrackses) {
       this.pkSolution = pkSolution;
//       this.ctUwells = ctUwells;
       this.ctExperiments = ctExperiments;
       this.name = name;
       this.ctDetectionses = ctDetectionses;
       this.ctTrackses = ctTrackses;
    }
   
    public int getPkSolution() {
        return this.pkSolution;
    }
    
    public void setPkSolution(int pkSolution) {
        this.pkSolution = pkSolution;
    }

//    public CtUwells getCtUwells() {
//        return this.ctUwells;
//    }
//    public void setCtUwells(CtUwells ctUwells) {
//        this.ctUwells = ctUwells;
//    }
    public CtExperiments getCtExperiments() {
        return this.ctExperiments;
    }
    public void setCtExperiments(CtExperiments ctExperiments) {
        this.ctExperiments = ctExperiments;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public Set getCtDetectionses() {
        return this.ctDetectionses;
    }
    
    public void setCtDetectionses(Set ctDetectionses) {
        this.ctDetectionses = ctDetectionses;
    }
    public Set getCtTrackses() {
        return this.ctTrackses;
    }
    
    public void setCtTrackses(Set ctTrackses) {
        this.ctTrackses = ctTrackses;
    }

}


