package au.com.nicta.ct.db.hibernate;
// Generated 24/01/2011 2:48:48 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * CtTracks generated by hbm2java
 */
public class CtTracks  implements java.io.Serializable {


     private int pkTrack;
     private CtSolutions ctSolutions;
     private Set ctTracksDetectionses = new HashSet(0);

    public CtTracks() {
    }
	
    public CtTracks(int pkTrack) {
        this.pkTrack = pkTrack;
    }
    public CtTracks(int pkTrack, CtSolutions ctSolutions, Set ctTracksDetectionses) {
       this.pkTrack = pkTrack;
       this.ctSolutions = ctSolutions;
       this.ctTracksDetectionses = ctTracksDetectionses;
    }
   
    public int getPkTrack() {
        return this.pkTrack;
    }
    
    public void setPkTrack(int pkTrack) {
        this.pkTrack = pkTrack;
    }
    public CtSolutions getCtSolutions() {
        return this.ctSolutions;
    }
    
    public void setCtSolutions(CtSolutions ctSolutions) {
        this.ctSolutions = ctSolutions;
    }
    public Set getCtTracksDetectionses() {
        return this.ctTracksDetectionses;
    }
    
    public void setCtTracksDetectionses(Set ctTracksDetectionses) {
        this.ctTracksDetectionses = ctTracksDetectionses;
    }

}


