package au.com.nicta.ct.db.hibernate;
// Generated 24/01/2011 2:48:48 PM by Hibernate Tools 3.2.1.GA



/**
 * CtUsersGroups generated by hbm2java
 */
public class CtUsersGroups  implements java.io.Serializable {


     private int pkUserGroup;
     private CtGroups ctGroups;
     private CtUsers ctUsers;

    public CtUsersGroups() {
    }

	
    public CtUsersGroups(int pkUserGroup) {
        this.pkUserGroup = pkUserGroup;
    }
    public CtUsersGroups(int pkUserGroup, CtGroups ctGroups, CtUsers ctUsers) {
       this.pkUserGroup = pkUserGroup;
       this.ctGroups = ctGroups;
       this.ctUsers = ctUsers;
    }
   
    public int getPkUserGroup() {
        return this.pkUserGroup;
    }
    
    public void setPkUserGroup(int pkUserGroup) {
        this.pkUserGroup = pkUserGroup;
    }
    public CtGroups getCtGroups() {
        return this.ctGroups;
    }
    
    public void setCtGroups(CtGroups ctGroups) {
        this.ctGroups = ctGroups;
    }
    public CtUsers getCtUsers() {
        return this.ctUsers;
    }
    
    public void setCtUsers(CtUsers ctUsers) {
        this.ctUsers = ctUsers;
    }




}


