package au.com.nicta.ct.db.hibernate;
// Generated 24/01/2011 2:48:48 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * CtUwells generated by hbm2java
 */
public class CtUwells  implements java.io.Serializable {


     private int pkUwell;
     private CtImages ctImages;
     private String position;
     private String boundary;
//     private Set ctSolutionses = new HashSet(0);

    public CtUwells() {
    }

	
    public CtUwells(int pkUwell) {
        this.pkUwell = pkUwell;
    }
    public CtUwells(int pkUwell, CtImages ctImages, String position, String boundary ) {//, Set ctSolutionses) {
       this.pkUwell = pkUwell;
       this.ctImages = ctImages;
       this.position = position;
       this.boundary = boundary;
//       this.ctSolutionses = ctSolutionses;
    }
   
    public int getPkUwell() {
        return this.pkUwell;
    }
    
    public void setPkUwell(int pkUwell) {
        this.pkUwell = pkUwell;
    }
    public CtImages getCtImages() {
        return this.ctImages;
    }
    
    public void setCtImages(CtImages ctImages) {
        this.ctImages = ctImages;
    }
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }
    public String getBoundary() {
        return this.boundary;
    }
    
    public void setBoundary(String boundary) {
        this.boundary = boundary;
    }

//    public Set getCtSolutionses() {
//        return this.ctSolutionses;
//    }
//    public void setCtSolutionses(Set ctSolutionses) {
//        this.ctSolutionses = ctSolutionses;
//    }

}


